/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firmansyah.imam.aplikasi.uts;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Imam Firmansyah
 */
public class FormPelanggan extends javax.swing.JFrame {

    /**
     * Creates new form FormPelanggan
     */
    public FormPelanggan() {
        initComponents();

        inputIdPelanggan.setEditable(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPelanggan = new javax.swing.JTable();
        labelIdPelanggan = new javax.swing.JLabel();
        labelNamaPelanggan = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelNoTelp = new javax.swing.JLabel();
        labelNoIdentitas = new javax.swing.JLabel();
        inputIdPelanggan = new javax.swing.JTextField();
        inputNamaPelanggan = new javax.swing.JTextField();
        inputNoTelepon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        inputNoIdentitas = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnFormSewa = new javax.swing.JButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Pelaggan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "Nama Pelanggan", "Alamat", "No. Telepon", "No. Identitas", "ID Pelanggan"
            }
        ));
        tblPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPelanggan);

        labelIdPelanggan.setText("ID Pelanggan");

        labelNamaPelanggan.setText("Nama Pelanggan");

        labelAlamat.setText("Alamat");

        labelNoTelp.setText("No. Telepon");

        labelNoIdentitas.setText("No. Identitas");

        inputAlamat.setColumns(20);
        inputAlamat.setRows(2);
        jScrollPane1.setViewportView(inputAlamat);

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        btnFormSewa.setText("Form Sewa");
        btnFormSewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFormSewaActionPerformed(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKeluarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdPelanggan)
                            .addComponent(labelNamaPelanggan)
                            .addComponent(labelAlamat)
                            .addComponent(labelNoTelp)
                            .addComponent(labelNoIdentitas))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputIdPelanggan)
                                .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputNoIdentitas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                .addComponent(inputNoTelepon, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)))
                        .addGap(0, 134, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnTambah, btnUbah});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormSewa, btnKeluar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdPelanggan)
                    .addComponent(inputIdPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPelanggan)
                    .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelAlamat)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNoTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoTelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNoIdentitas)
                    .addComponent(inputNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnHapus)
                    .addComponent(btnRefresh))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSewa)
                    .addComponent(btnKeluar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(653, 523));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // munculkan data kendaraan
        showDataPelanggan();
    }//GEN-LAST:event_formWindowActivated

    private void tblPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPelangganMouseClicked
        int row = tblPelanggan.getSelectedRow();
        String tblKendaraanID = (tblPelanggan.getModel().getValueAt(row, 5).toString());
        System.out.println("ID Kendaraan : " + tblKendaraanID);

        try {
            showDataPelangganById(Integer.parseInt(tblKendaraanID));
        } catch (ParseException ex) {
            Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblPelangganMouseClicked

    private void btnFormSewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFormSewaActionPerformed
        this.dispose();
        System.out.println("Panggil Form Sewa");

        // memanggil form Sewa
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnFormSewaActionPerformed

    private void btnKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKeluarActionPerformed
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar? ", "Konfirmasi", dialogButton);
        if (dialogResult == 0) {
            System.out.println("Quit");
            this.dispose();
        } else {
            System.out.println("cancel");
        }
    }//GEN-LAST:event_btnKeluarActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String namaPelanggan = inputNamaPelanggan.getText().replaceAll(" ", "%20");
        String alamat = inputAlamat.getText().replaceAll(" ", "%20");
        String noTelp = inputNoTelepon.getText().replaceAll(" ", "%20");
        String noIdentitas = inputNoIdentitas.getText().replaceAll(" ", "%20");

        btnUbah.setEnabled(false);

        if (namaPelanggan.isEmpty() || alamat.isEmpty() || noTelp.isEmpty() || noIdentitas.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Informasi", JOptionPane.ERROR_MESSAGE);

        } else {

            String url = Path.serverURL + "/pelanggan/create/" + namaPelanggan + "/" + alamat + "/" + noTelp + "/" + noIdentitas;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                cleanFormPelanggan();

                JOptionPane.showMessageDialog(this, "Data Berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                // munculkan data kendaraan
                showDataPelanggan();

            } catch (IOException ex) {
                Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String idPelanggan = inputIdPelanggan.getText();
        String namaPelanggan = inputNamaPelanggan.getText().replaceAll(" ", "%20");
        String alamat = inputAlamat.getText().replaceAll(" ", "%20");
        String noTelp = inputNoTelepon.getText().replaceAll(" ", "%20");
        String noIdentitas = inputNoIdentitas.getText().replaceAll(" ", "%20");

        btnHapus.setEnabled(false);

        if (namaPelanggan.isEmpty() || alamat.isEmpty() || noTelp.isEmpty() || noIdentitas.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Informasi", JOptionPane.ERROR_MESSAGE);

            btnTambah.setEnabled(false);

        } else {

            String url = Path.serverURL + "/pelanggan/update/" + idPelanggan + "/" + namaPelanggan + "/" + alamat + "/" + noTelp + "/" + noIdentitas;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                // bersihkan form
                cleanFormPelanggan();

                btnTambah.setEnabled(true);
                btnUbah.setEnabled(false);

                JOptionPane.showMessageDialog(this, "Data Berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                // munculkan data kendaraan
                showDataPelanggan();

            } catch (IOException ex) {
                Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String idPelanggan = inputIdPelanggan.getText();
        System.out.println("Memilih ID : " + idPelanggan);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data ini? ", "Konfirmasi", dialogButton);

        if (dialogResult == 0) {
            String url = Path.serverURL + "/pelanggan/delete/" + idPelanggan;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                if (data.equals("1")) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                    System.out.println("Menghapus Data ID : " + idPelanggan);

                } else {
                    JOptionPane.showMessageDialog(this, "Data Tidak Berhasil dihapus", "Informasi", JOptionPane.ERROR_MESSAGE);
                }

            } catch (IOException ex) {
                Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);

                JOptionPane.showMessageDialog(this, "Data Tidak Bisa dihapus\nKarena Memiliki Relasi dengan Data Lainnya", "Informasi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("Tidak Menghapus : " + idPelanggan);
        }

        // munculkan data kendaraan
        showDataPelanggan();

        // bersihkan form
        cleanFormPelanggan();

        btnTambah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // munculkan data kendaraan
        showDataPelanggan();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPelanggan().setVisible(true);
            }
        });
    }

    // function munculkan data kendaraan
    public void showDataPelanggan() {
        try {
            getDataURL dataurl = new getDataURL();
            DefaultTableModel model = (DefaultTableModel) tblPelanggan.getModel();

            model.setRowCount(0);

            String url = Path.serverURL + "/pelanggan/show/";

            String data = dataurl.getData(url);

            Object obj = JSONValue.parse(data);
            JSONArray dataArray = (JSONArray) obj;

            System.out.println("Banyak datanya : " + dataArray.size());

            for (int i = 0; i < dataArray.size(); i++) {
                JSONObject getData = (JSONObject) dataArray.get(i);

                Object[] row = {
                    i + 1,
                    getData.get("nama_pelanggan"),
                    getData.get("alamat"),
                    getData.get("no_telp"),
                    getData.get("no_identitas"),
                    getData.get("id"),};

                model.addRow(row);
            }
        } catch (IOException ex) {
            Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // function munculkan data kendaraan by id
    public void showDataPelangganById(int id) throws ParseException {
        try {
            getDataURL dataurl = new getDataURL();

            String url = Path.serverURL + "/pelanggan/show/" + id;

            String data = dataurl.getData(url);

            Object obj = JSONValue.parse(data);
            JSONArray dataArray = (JSONArray) obj;

            JSONObject getData = (JSONObject) dataArray.get(0);

            Object nama_pelanggan = getData.get("nama_pelanggan");
            Object alamat = getData.get("alamat");
            Object no_telp = getData.get("no_telp");
            Object no_identitas = getData.get("no_identitas");
            Object id_pelanggan = getData.get("id");

            inputNamaPelanggan.setText((String) nama_pelanggan);
            inputAlamat.setText((String) alamat);
            inputNoTelepon.setText((String) no_telp);
            inputNoIdentitas.setText((String) no_identitas);
            inputIdPelanggan.setText((String) id_pelanggan.toString());

            btnTambah.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(FormPelanggan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // function clean Form Pelanggan
    public void cleanFormPelanggan() {
        inputIdPelanggan.setText("");
        inputNamaPelanggan.setText("");
        inputAlamat.setText("");
        inputNoTelepon.setText("");
        inputNoIdentitas.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFormSewa;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputIdPelanggan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputNoTelepon;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelIdPelanggan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoIdentitas;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JTable tblPelanggan;
    // End of variables declaration//GEN-END:variables
}
