/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firmansyah.imam.aplikasi.uts;

import java.io.IOException;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.joda.time.DateTime;
import org.joda.time.Days;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.JSONParser;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Imam Firmansyah
 */
public class FormTransaksi extends javax.swing.JFrame {

    /**
     * Creates new form FormTransaksi
     */
    public FormTransaksi() {
        initComponents();

        inputNoSewa.setEditable(false);
        inputNamaPelanggan.setEditable(false);
        inputAlamat.setEditable(false);
        inputNoTelp.setEditable(false);
        inputNoIdentitas.setEditable(false);
        inputDariTanggal.setEditable(false);
        inputSampai.setEditable(false);
        inputHariSewa.setEditable(false);
        inputNamaKendaraan.setEditable(false);
        inputNoPolisi.setEditable(false);
        inputTahunKendaraan.setEditable(false);
        inputHari.setEditable(false);
        inputBiayaSewa.setEditable(false);
        inputBiayaTotal.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelNoSewa = new javax.swing.JLabel();
        labelNamaPelanggan = new javax.swing.JLabel();
        labelAlamat = new javax.swing.JLabel();
        labelNoTelp = new javax.swing.JLabel();
        labelNoIdentitas = new javax.swing.JLabel();
        inputNoSewa = new javax.swing.JTextField();
        inputNamaPelanggan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        inputAlamat = new javax.swing.JTextArea();
        inputNoTelp = new javax.swing.JTextField();
        inputNoIdentitas = new javax.swing.JTextField();
        labelLamaSewa = new javax.swing.JLabel();
        labelDariTanggal = new javax.swing.JLabel();
        inputHari = new javax.swing.JTextField();
        labelHari = new javax.swing.JLabel();
        inputDariTanggal = new javax.swing.JTextField();
        labelSampai = new javax.swing.JLabel();
        inputSampai = new javax.swing.JTextField();
        inputHariSewa = new javax.swing.JTextField();
        labelBiayaSewa = new javax.swing.JLabel();
        labelKali = new javax.swing.JLabel();
        inputBiayaSewa = new javax.swing.JTextField();
        inputBiayaTotal = new javax.swing.JTextField();
        labelRpSewa = new javax.swing.JLabel();
        labelRpBiaya = new javax.swing.JLabel();
        labelNamaKendaraan = new javax.swing.JLabel();
        inputNamaKendaraan = new javax.swing.JTextField();
        inputNoPolisi = new javax.swing.JTextField();
        labelNoPolisi = new javax.swing.JLabel();
        labelTahunKendaraan = new javax.swing.JLabel();
        inputTahunKendaraan = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        labelTanggalTransaksi = new javax.swing.JLabel();
        btnSelesai = new javax.swing.JButton();
        btnKembali = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Transaksi");

        labelNoSewa.setText("No. Sewa");

        labelNamaPelanggan.setText("Nama Pelanggan");

        labelAlamat.setText("Alamat");

        labelNoTelp.setText("No. Telp");

        labelNoIdentitas.setText("No. Identitas");

        inputAlamat.setColumns(20);
        inputAlamat.setRows(4);
        jScrollPane1.setViewportView(inputAlamat);

        labelLamaSewa.setText("Lama Sewa");

        labelDariTanggal.setText("Dari Tanggal");

        labelHari.setText("Hari");

        labelSampai.setText("Sampai");

        labelBiayaSewa.setText("Biaya Sewa");

        labelKali.setText("x");

        labelRpSewa.setText("Rp");

        labelRpBiaya.setText("Rp");

        labelNamaKendaraan.setText("Nama Kendaraan");

        labelNoPolisi.setText("No. Polisi");

        labelTahunKendaraan.setText("Tahun Kendaraan");

        labelTanggalTransaksi.setText("2015-11-21 17:13:27");

        btnSelesai.setText("Sewa Selesai");
        btnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelesaiActionPerformed(evt);
            }
        });

        btnKembali.setText("Kembali");
        btnKembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKembaliMouseClicked(evt);
            }
        });

        jLabel1.setText("Tanggal Transaksi");

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSelesai)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnHapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                        .addComponent(btnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNoSewa)
                            .addComponent(labelNamaPelanggan)
                            .addComponent(labelAlamat)
                            .addComponent(labelNoTelp)
                            .addComponent(labelNoIdentitas)
                            .addComponent(labelLamaSewa)
                            .addComponent(labelBiayaSewa)
                            .addComponent(labelNamaKendaraan)
                            .addComponent(labelNoPolisi)
                            .addComponent(labelTahunKendaraan)
                            .addComponent(jLabel1))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(inputNoIdentitas)
                            .addComponent(inputNamaPelanggan)
                            .addComponent(inputNoTelp)
                            .addComponent(inputNoSewa)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDariTanggal)
                                    .addComponent(labelSampai))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(inputBiayaSewa, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(inputDariTanggal)
                                    .addComponent(inputSampai)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelRpBiaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(inputBiayaTotal))
                            .addComponent(inputNamaKendaraan)
                            .addComponent(inputNoPolisi)
                            .addComponent(inputTahunKendaraan)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelTanggalTransaksi)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputHari, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelHari))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(inputHariSewa, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelKali)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(labelRpSewa)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnKembali, btnSelesai});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoSewa)
                    .addComponent(inputNoSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaPelanggan)
                    .addComponent(inputNamaPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelAlamat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNoTelp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoTelp))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNoIdentitas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoIdentitas))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNamaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaKendaraan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNoPolisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputTahunKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTahunKendaraan))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelLamaSewa)
                    .addComponent(inputHari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelHari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDariTanggal)
                    .addComponent(inputDariTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelSampai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHariSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBiayaSewa)
                    .addComponent(labelKali)
                    .addComponent(inputBiayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRpSewa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputBiayaTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRpBiaya))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTanggalTransaksi)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSelesai)
                    .addComponent(btnKembali)
                    .addComponent(btnHapus))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKembaliMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");

        // memanggil form Sewa
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnKembaliMouseClicked

    private void btnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelesaiActionPerformed
        String id_transaksi = inputNoSewa.getText();

        System.out.println("Ubah Status untuk ID : " + id_transaksi);
        try {
            getDataURL dataurl = new getDataURL();

            String url = Path.serverURL + "/sewa/update/" + id_transaksi;

            String data = dataurl.getData(url);
            System.out.println(data);

            btnSelesai.setEnabled(false);

            JOptionPane.showMessageDialog(this, "Status Penyewaan Telah Selesai", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        } catch (IOException ex) {
            Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSelesaiActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String id_transaksi = inputNoSewa.getText();

        System.out.println("Delete untuk ID : " + id_transaksi);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data ini? ", "Konfirmasi", dialogButton);

        if (dialogResult == 0) {

            try {
                getDataURL dataurl = new getDataURL();

                String url = Path.serverURL + "/sewa/delete/" + id_transaksi;

                String data = dataurl.getData(url);
                System.out.println(data);

                btnSelesai.setEnabled(false);

                JOptionPane.showMessageDialog(this, "Data Telah dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                this.dispose();
                System.out.println("Panggil Form Sewa");

                // memanggil form Sewa
                FormSewa callForm = new FormSewa();
                callForm.setLocationRelativeTo(null);
                callForm.setVisible(true);

            } catch (IOException ex) {
                Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            System.out.println("Delete Dibatalkan : " + id_transaksi);
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormTransaksi().setVisible(true);
            }
        });
    }

    public void detailTransaksi(String id_transaksi) throws ParseException {
        System.out.println("Set ID nya : " + id_transaksi);

        try {

            getDataURL dataurl = new getDataURL();

            String url = Path.serverURL + "/sewa/show/" + id_transaksi;

            String data = dataurl.getData(url);

            Object obj = JSONValue.parse(data);
            JSONArray dataArray = (JSONArray) obj;

            JSONObject getData = (JSONObject) dataArray.get(0);

            Object id_sewa = getData.get("id");
            Object dari_tanggal = getData.get("tanggal_mulai");
            Object sampai_tanggal = getData.get("tanggal_akhir");
            Object tanggal_sewa = getData.get("tanggal_sewa");
            Object kendaraan = getData.get("kendaraan");
            Object pelanggan = getData.get("pelanggan");
            Object status_sewa = getData.get("status");

            if (status_sewa.equals("1")) {
                btnSelesai.setEnabled(false);
            }

            JSONObject getJsonKendaraan = (JSONObject) new JSONParser().parse(kendaraan.toString());
            JSONObject getJsonPelanggan = (JSONObject) new JSONParser().parse(pelanggan.toString());

            Object nama_kendaraan = getJsonKendaraan.get("nama_kendaraan");
            Object no_polisi = getJsonKendaraan.get("no_polisi");
            Object tahun_kendaraan = getJsonKendaraan.get("tahun_kendaraan");
            Object biaya_sewa = getJsonKendaraan.get("biaya_sewa");

            Object nama_pelanggan = getJsonPelanggan.get("nama_pelanggan");
            Object alamat = getJsonPelanggan.get("alamat");
            Object no_telp = getJsonPelanggan.get("no_telp");
            Object no_identitas = getJsonPelanggan.get("no_identitas");

            String tgl_mulai = dari_tanggal.toString();
            String tgl_akhir = sampai_tanggal.toString();

            int days = Days.daysBetween(new DateTime(tgl_mulai), new DateTime(tgl_akhir)).getDays() + 1;
            int total_biaya_sewa = Integer.parseInt(biaya_sewa.toString()) * days;

            DecimalFormat df = new DecimalFormat("###,###.###");
            String biaya_sewaConvert = df.format(Integer.parseInt(biaya_sewa.toString()));
            String total_biayaConvert = df.format(total_biaya_sewa);

            inputNoSewa.setText(id_sewa.toString());
            inputDariTanggal.setText(dari_tanggal.toString());
            inputSampai.setText(sampai_tanggal.toString());
            inputHari.setText(String.valueOf(days));
            inputHariSewa.setText(String.valueOf(days));

            inputNamaKendaraan.setText(nama_kendaraan.toString());
            inputNoPolisi.setText(no_polisi.toString());
            inputTahunKendaraan.setText(tahun_kendaraan.toString());

            inputNamaPelanggan.setText(nama_pelanggan.toString());
            inputAlamat.setText(alamat.toString());
            inputNoTelp.setText(no_telp.toString());
            inputNoIdentitas.setText(no_identitas.toString());

            labelTanggalTransaksi.setText(tanggal_sewa.toString());

            inputBiayaSewa.setText(biaya_sewaConvert);
            inputBiayaTotal.setText(total_biayaConvert);

        } catch (IOException ex) {

            Logger.getLogger(FormTransaksi.class.getName()).log(Level.SEVERE, null, ex);

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JToggleButton btnKembali;
    private javax.swing.JButton btnSelesai;
    private javax.swing.JTextArea inputAlamat;
    private javax.swing.JTextField inputBiayaSewa;
    private javax.swing.JTextField inputBiayaTotal;
    private javax.swing.JTextField inputDariTanggal;
    private javax.swing.JTextField inputHari;
    private javax.swing.JTextField inputHariSewa;
    private javax.swing.JTextField inputNamaKendaraan;
    private javax.swing.JTextField inputNamaPelanggan;
    private javax.swing.JTextField inputNoIdentitas;
    private javax.swing.JTextField inputNoPolisi;
    private javax.swing.JTextField inputNoSewa;
    private javax.swing.JTextField inputNoTelp;
    private javax.swing.JTextField inputSampai;
    private javax.swing.JTextField inputTahunKendaraan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel labelAlamat;
    private javax.swing.JLabel labelBiayaSewa;
    private javax.swing.JLabel labelDariTanggal;
    private javax.swing.JLabel labelHari;
    private javax.swing.JLabel labelKali;
    private javax.swing.JLabel labelLamaSewa;
    private javax.swing.JLabel labelNamaKendaraan;
    private javax.swing.JLabel labelNamaPelanggan;
    private javax.swing.JLabel labelNoIdentitas;
    private javax.swing.JLabel labelNoPolisi;
    private javax.swing.JLabel labelNoSewa;
    private javax.swing.JLabel labelNoTelp;
    private javax.swing.JLabel labelRpBiaya;
    private javax.swing.JLabel labelRpSewa;
    private javax.swing.JLabel labelSampai;
    private javax.swing.JLabel labelTahunKendaraan;
    private javax.swing.JLabel labelTanggalTransaksi;
    // End of variables declaration//GEN-END:variables
}
