/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.firmansyah.imam.aplikasi.uts;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.JSONValue;
import org.json.simple.parser.ParseException;

/**
 *
 * @author Imam Firmansyah
 */
public class FormKendaraan extends javax.swing.JFrame {

    /**
     * Creates new form FormKendaraan
     */
    public FormKendaraan() {
        initComponents();

        inputIdKendaraan.setEditable(false);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblKendaraan = new javax.swing.JTable();
        labelNamaKendaraan = new javax.swing.JLabel();
        inputNamaKendaraan = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        labelNoPolisi = new javax.swing.JLabel();
        inputNoPolisi = new javax.swing.JTextField();
        labelTahunKendaraan = new javax.swing.JLabel();
        inputTahunKendaraan = new javax.swing.JTextField();
        labelBiayaSewa = new javax.swing.JLabel();
        inputBiayaSewa = new javax.swing.JTextField();
        btnUbah = new javax.swing.JButton();
        labelIdKendaraan = new javax.swing.JLabel();
        inputIdKendaraan = new javax.swing.JTextField();
        btnHapus = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnFormSewa = new javax.swing.JToggleButton();
        btnKeluar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Form Kendaraan");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        tblKendaraan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No", "No. Polisi", "Nama Kendaraan", "Tahun Kendaraan", "Biaya Sewa", "ID Kendaraan", "Status"
            }
        ));
        tblKendaraan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKendaraanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKendaraan);

        labelNamaKendaraan.setText("Nama Kendaraan");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        labelNoPolisi.setText("No. Polisi");

        labelTahunKendaraan.setText("Tahun Kendaraan");

        labelBiayaSewa.setText("Biaya Sewa");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        labelIdKendaraan.setText("ID Kendaraan");

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnFormSewa.setText("Form Sewa");
        btnFormSewa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFormSewaMouseClicked(evt);
            }
        });

        btnKeluar.setText("Keluar");
        btnKeluar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKeluarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 812, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNoPolisi)
                            .addComponent(labelNamaKendaraan)
                            .addComponent(labelTahunKendaraan)
                            .addComponent(labelBiayaSewa)
                            .addComponent(labelIdKendaraan))
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(inputIdKendaraan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE)
                                .addComponent(inputNoPolisi)
                                .addComponent(inputNamaKendaraan)
                                .addComponent(inputTahunKendaraan, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(inputBiayaSewa, javax.swing.GroupLayout.Alignment.LEADING))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnUbah)
                                .addGap(5, 5, 5)
                                .addComponent(btnHapus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRefresh)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnFormSewa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnKeluar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnHapus, btnRefresh, btnTambah, btnUbah});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnFormSewa, btnKeluar});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIdKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdKendaraan))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoPolisi)
                    .addComponent(inputNoPolisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaKendaraan)
                    .addComponent(inputNamaKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTahunKendaraan)
                    .addComponent(inputTahunKendaraan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelBiayaSewa))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(inputBiayaSewa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah)
                    .addComponent(btnUbah)
                    .addComponent(btnRefresh)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFormSewa)
                    .addComponent(btnKeluar))
                .addGap(44, 44, 44))
        );

        setSize(new java.awt.Dimension(848, 593));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // munculkan data kendaraan
        showDataKendaraan();
    }//GEN-LAST:event_formWindowActivated

    private void tblKendaraanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKendaraanMouseClicked
        int row = tblKendaraan.getSelectedRow();
        String tblKendaraanID = (tblKendaraan.getModel().getValueAt(row, 5).toString());
        System.out.println("ID Kendaraan : " + tblKendaraanID);

        try {
            showDataKendaraanById(Integer.parseInt(tblKendaraanID));
        } catch (ParseException ex) {
            Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tblKendaraanMouseClicked

    private void btnKeluarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKeluarMouseClicked
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Ingin Keluar? ", "Konfirmasi", dialogButton);
        if (dialogResult == 0) {
            System.out.println("Quit");
            this.dispose();
        } else {
            System.out.println("cancel");
        }
    }//GEN-LAST:event_btnKeluarMouseClicked

    private void btnFormSewaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFormSewaMouseClicked
        this.dispose();
        System.out.println("Panggil Form Sewa");

        // memanggil form Sewa
        FormSewa callForm = new FormSewa();
        callForm.setLocationRelativeTo(null);
        callForm.setVisible(true);
    }//GEN-LAST:event_btnFormSewaMouseClicked

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        String noPolisi = inputNoPolisi.getText().replaceAll(" ", "%20");
        String namaKendaraan = inputNamaKendaraan.getText().replaceAll(" ", "%20");
        String tahunKendaraan = inputTahunKendaraan.getText();
        String biayaSewa = inputBiayaSewa.getText();

        btnUbah.setEnabled(false);
        
        if (noPolisi.isEmpty() || namaKendaraan.isEmpty() || tahunKendaraan.isEmpty() || biayaSewa.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Informasi", JOptionPane.ERROR_MESSAGE);

        } else if (isNumeric(biayaSewa) == false || isNumeric(tahunKendaraan) == false ) {

            JOptionPane.showMessageDialog(this, "Masukan Biaya Sewa dan Tahun Kendaraan dengan Angka", "Informasi", JOptionPane.ERROR_MESSAGE);

        } else {

            String url = Path.serverURL + "/kendaraan/create/" + noPolisi + "/" + namaKendaraan + "/" + tahunKendaraan + "/" + biayaSewa;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                cleanFormKendaraan();

                JOptionPane.showMessageDialog(this, "Data Berhasil disimpan", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                // munculkan data kendaraan
                showDataKendaraan();

            } catch (IOException ex) {
                Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        String idKendaraan = inputIdKendaraan.getText();
        String noPolisi = inputNoPolisi.getText().replaceAll(" ", "%20");
        String namaKendaraan = inputNamaKendaraan.getText().replaceAll(" ", "%20");
        String tahunKendaraan = inputTahunKendaraan.getText().replaceAll(" ", "%20");
        String biayaSewa = inputBiayaSewa.getText().replaceAll(" ", "%20");

        btnHapus.setEnabled(false);
        
        if (noPolisi.isEmpty() || namaKendaraan.isEmpty() || tahunKendaraan.isEmpty() || biayaSewa.isEmpty()) {

            JOptionPane.showMessageDialog(this, "Data Tidak Boleh Kosong", "Informasi", JOptionPane.ERROR_MESSAGE);
            
             btnTambah.setEnabled(false);
             
        } else if (isNumeric(biayaSewa) == false || isNumeric(tahunKendaraan) == false ) {

            JOptionPane.showMessageDialog(this, "Masukan Biaya Sewa dan Tahun Kendaraan dengan Angka", "Informasi", JOptionPane.ERROR_MESSAGE);

        } else {

            String url = Path.serverURL + "/kendaraan/update/" + idKendaraan + "/" + noPolisi + "/" + namaKendaraan + "/" + tahunKendaraan + "/" + biayaSewa;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                // bersihkan form
                cleanFormKendaraan();

                btnTambah.setEnabled(true);
                btnUbah.setEnabled(false);

                JOptionPane.showMessageDialog(this, "Data Berhasil diubah", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                // munculkan data kendaraan
                showDataKendaraan();

            } catch (IOException ex) {
                Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        String idKendaraan = inputIdKendaraan.getText();
        System.out.println("Memilih ID : " + idKendaraan);

        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult;
        dialogResult = JOptionPane.showConfirmDialog(this, "Anda yakin Menghapus Data ini? ", "Konfirmasi", dialogButton);

        if (dialogResult == 0) {
            String url = Path.serverURL + "/kendaraan/delete/" + idKendaraan;

            getDataURL dataurl = new getDataURL();

            try {
                String data = dataurl.getData(url);
                System.out.println(data);

                if (data.equals("1")) {
                    JOptionPane.showMessageDialog(this, "Data Berhasil dihapus", "Informasi", JOptionPane.INFORMATION_MESSAGE);

                    System.out.println("Menghapus Data ID : " + idKendaraan);

                } else {
                    JOptionPane.showMessageDialog(this, "Data Tidak Berhasil dihapus", "Informasi", JOptionPane.ERROR_MESSAGE);
                }

            } catch (IOException ex) {
                Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);

                JOptionPane.showMessageDialog(this, "Data Tidak Bisa dihapus\nKarena Memiliki Relasi dengan Data Lainnya", "Informasi", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            System.out.println("Tidak Menghapus : " + idKendaraan);
        }

        // munculkan data kendaraan
        showDataKendaraan();

        // bersihkan form
        cleanFormKendaraan();

        btnTambah.setEnabled(true);
        btnUbah.setEnabled(false);
        btnHapus.setEnabled(false);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // munculkan data kendaraan
        showDataKendaraan();
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormKendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormKendaraan().setVisible(true);
            }
        });
    }

    // function munculkan data kendaraan
    public void showDataKendaraan() {
        try {
            getDataURL dataurl = new getDataURL();
            DefaultTableModel model = (DefaultTableModel) tblKendaraan.getModel();

            model.setRowCount(0);

            String url = Path.serverURL + "/kendaraan/show";

            String data = dataurl.getData(url);

            Object obj = JSONValue.parse(data);
            JSONArray dataArray = (JSONArray) obj;

            System.out.println("Banyak datanya : " + dataArray.size());

            for (int i = 0; i < dataArray.size(); i++) {
                JSONObject getData = (JSONObject) dataArray.get(i);

                String cek_status = getData.get("status").toString();

                if (cek_status.equals("0")) {
                    cek_status = "Tidak Tersedia";
                } else {
                    cek_status = "Tersedia";
                }

                Object[] row = {
                    i + 1,
                    getData.get("no_polisi"),
                    getData.get("nama_kendaraan"),
                    getData.get("tahun_kendaraan"),
                    getData.get("biaya_sewa"),
                    getData.get("id"),
                    cek_status
                };

                model.addRow(row);
            }
        } catch (IOException ex) {
            Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // function munculkan data kendaraan by id
    public void showDataKendaraanById(int id) throws ParseException {
        try {
            getDataURL dataurl = new getDataURL();

            String url = Path.serverURL + "/kendaraan/show/" + id;

            String data = dataurl.getData(url);

            Object obj = JSONValue.parse(data);
            JSONArray dataArray = (JSONArray) obj;

            JSONObject getData = (JSONObject) dataArray.get(0);

            Object no_polisi = getData.get("no_polisi");
            Object nama_kendaraan = getData.get("nama_kendaraan");
            Object tahun_kendaraan = getData.get("tahun_kendaraan");
            Object biaya_sewa = getData.get("biaya_sewa");
            Object id_kendaraan = getData.get("id");

            inputNoPolisi.setText((String) no_polisi);
            inputNamaKendaraan.setText((String) nama_kendaraan);
            inputTahunKendaraan.setText((String) tahun_kendaraan);
            inputBiayaSewa.setText((String) biaya_sewa);
            inputIdKendaraan.setText((String) id_kendaraan.toString());

            btnTambah.setEnabled(false);
            btnUbah.setEnabled(true);
            btnHapus.setEnabled(true);

        } catch (IOException ex) {
            Logger.getLogger(FormKendaraan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // function clean Form Kendaraan
    public void cleanFormKendaraan() {
        inputIdKendaraan.setText("");
        inputNoPolisi.setText("");
        inputNamaKendaraan.setText("");
        inputTahunKendaraan.setText("");
        inputBiayaSewa.setText("");
    }

    public boolean isNumeric(String s) {
        return s.matches("[-+]?\\d*\\.?\\d+");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnFormSewa;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKeluar;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField inputBiayaSewa;
    private javax.swing.JTextField inputIdKendaraan;
    private javax.swing.JTextField inputNamaKendaraan;
    private javax.swing.JTextField inputNoPolisi;
    private javax.swing.JTextField inputTahunKendaraan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelBiayaSewa;
    private javax.swing.JLabel labelIdKendaraan;
    private javax.swing.JLabel labelNamaKendaraan;
    private javax.swing.JLabel labelNoPolisi;
    private javax.swing.JLabel labelTahunKendaraan;
    private javax.swing.JTable tblKendaraan;
    // End of variables declaration//GEN-END:variables
}
